#!/bin/bash
sudo ip link set dev enp0s3 down
sudo ip link set dev enp0s3 address $1
sudo ip link set dev enp0s3 up

mac=$(ip link show enp0s3 | grep ether | cut -d ' ' -f6)

if [ $1 = $mac ]
then
echo "\033[32mYour MAC successfully changed on $1\033[0m"
else
echo "\033[31mError\033[0m"
fi